global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'sensor_pipeline'
    static_configs:
      - targets: ['localhost:9090']  # Prometheus metrics from our pipeline

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']

  - job_name: 'influxdb'
    static_configs:
      - targets: ['influxdb:8086']

  - job_name: 'timescaledb'
    static_configs:
      - targets: ['timescaledb:5432']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow-webserver:8080'] 